spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.2"
dummy:
  commit: ignore

accounts:
  message: "Welcome to the XYZ Bank accounts related production services"
  contactDetails:
    name: "Ashish Kumar Prod"
    email: "{cipher}01ee38d41ef03b45bf66db01c75dadfc146aff712f4c7f40e919135cbdd91003"
  contactNumbers:
    - "0987654321"
    - "2468013579"  
