spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${Mongo_DB:accounts}

  
build: 
  version: "1.0"
server:
  port: 8091

accounts:
  message: "Welcome to the XYZ Bank accounts related services"
  contactDetails:
    name: "Ashish Kumar"
    email: "xyz@xyz.com"
  contactNumbers:
    - "1234567890"
    - "0987654321"  
    