
spring:
  activate:
    on-profile: qa
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${Mongo_DB:loanDB}

laons:
  message: "Welcome to XYZ Bank loans related qa services"
  contactDetails:
    name: "Shubham Dhiman"
    email: "{cipher}01ee38d41ef03b45bf66db01c75dadfc146aff712f4c7f40e919135cbdd91003"
  contactNumbers:
    - "0987122221"
    - "2462103229"  
