
spring:
  activate:
    on-profile: prod
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${Mongo_DB:loanDB}

loans:
  message: "Welcome to XYZ Bank loans related prod services"
  contactDetails:
    name: "Shubham Dhiman"
    email: "{cipher}01ee38d41ef03b45bf66db01c75dadfc146aff712f4c7f40e919135cbdd91003"
  contactNumbers:
    - "0987124321"
    - "2462103579"  

